apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopy-deployment
  labels:
    app: shopy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopy
  template:
    metadata:
      labels:
        app: shopy
    spec:
      containers:
        - name: shopyserver
          image: danikeys/shopy:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql_database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql_host
          resources:
            # limits:
            #   memory: '128Mi'
            #   cpu: '500m'
          ports:
            - containerPort: 3000
